name: example
description: Example app for flutter_form_builder package
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  flutter_form_builder:
    path: ../
  form_builder_validators:
    path: ../../form_builder_validators/
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

